# Ansible playbook for 3X-UI Panel installation
---
- name: Installation | 3X-UI
  hosts: all
  become: true
  remote_user: root
  gather_facts: true
  vars:
    web_port: 6763
    home_user: your_home_user
  roles:
    - 3xui-installation

- name: Prompt for Amnezia VPN WebUI installation
  hosts: all
  become: true
  remote_user: root
  gather_facts: true
  tasks:
    - name: Ask if Amnezia VPN WebUI should be installed
      ansible.builtin.pause:
        prompt: "Install WebUI for Amnezia VPN? (YES/NO)"
      register: amnezia_wg_needed

    - name: Fail if user chooses NO
      ansible.builtin.fail:
        msg: "YouYE chose not to install Amnezia VPN WebUI. Stopping playbook."
      when: amnezia_wg_needed.user_input | default('NO') | upper == 'NO'

- name: Installation | amnezia-wg-easy
  hosts: all
  become: true
  remote_user: root
  gather_facts: true
  vars:
    awg_port: 512820
    awgui_port: 51821
    password_ui: y0ursEcurepAsswo0d
    jc: 3
    jmin: 40
    jmax: 70
    # s1: 50
    # s2: 50
  roles:
    - amnezia-wg-easy
  tags: amnezia-wg-easy
