# Ansible playbook for 3X-UI Panel installation
---
- name: Installation | 3X-UI
  hosts: vpn_servers
  become: true
  remote_user: root
  gather_facts: true
  roles:
    - 3xui-installation
    - caddy-server

- name: Prompt for Amnezia VPN WebUI installation
  hosts: vpn_servers
  become: true
  remote_user: root
  gather_facts: true
  tasks:
    - name: Ask if Amnezia VPN WebUI should be installed
      ansible.builtin.pause:
        prompt: "Install WebUI for Amnezia VPN? (YES/NO)"
      register: amnezia_wg_needed

    - name: Fail if user chooses NO
      ansible.builtin.fail:
        msg: "You chose not to install Amnezia VPN WebUI. Stopping playbook."
      when: amnezia_wg_needed.user_input | default('NO') | upper == 'NO'

- name: Installation | amnezia-wg-easy
  hosts: vpn_servers
  become: true
  remote_user: root
  gather_facts: true
  roles:
    - amnezia-wg-easy
    - caddy-server
  tags: amnezia-wg-easy

- name: Installation | Caddy web server
  hosts: vpn_servers
  become: true
  remote_user: root
  gather_facts: true
  roles:
    - caddy-server
  tags: caddy-server
