---
- name: Install Nerd font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/3270.zip
    dest: /tmp/nerd_font.zip
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: "0644"

- name: Create dir for storage fonts
  ansible.builtin.file:
    path: /usr/share/fonts
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Unzip downloaded fonts
  ansible.builtin.unarchive:
    src: /tmp/nerd_font.zip
    dest: /usr/share/fonts
    remote_src: true

- name: Rebuild the font cache
  ansible.builtin.command: fc-cache -fvf
  changed_when: false

- name: Check OMZ folder
  ansible.builtin.stat:
    path: "/home/{{ home_user }}/.oh-my-zsh"
  register: omz_folder

- name: Get Oh-My-ZSH
  become: true
  become_user: "{{ home_user }}"
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
  register: omz_result
  when: not omz_folder.stat.exists
  changed_when: false

- name: OMZ output
  ansible.builtin.debug:
    msg: omz_result.stdout

- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ home_user }}/.oh-my-zsh/custom/themes/powerlevel10k
    update: true

- name: Set Powerlevel10k theme in .zshrc
  ansible.builtin.lineinfile:
    path: /home/{{ home_user }}/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

- name: Copy files for root
  block:
    - name: Copy .zshrc
      ansible.builtin.copy:
        remote_src: true
        src: "/home/{{ home_user }}/.zshrc"
        dest: /root/.zshrc
        owner: root
        group: root
        mode: "0644"

    - name: Copy .oh-my-zsh
      ansible.builtin.copy:
        remote_src: true
        src: "/home/{{ home_user }}/.oh-my-zsh"
        dest: /root/
        owner: root
        group: root
        mode: "0644"

    - name: Copy powerlevel10k
      ansible.builtin.copy:
        remote_src: true
        src: /home/{{ home_user }}/.oh-my-zsh/custom/themes/powerlevel10k
        dest: /root/.oh-my-zsh/custom/themes/powerlevel10k
        mode: "0755"

- name: Change shell for root
  ansible.builtin.user:
    name: root
    shell: /bin/zsh
