---
# handlers file for 3xui-installation
- name: Reload SSH
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban.service
    state: restarted

- name: Reload nftables
  ansible.builtin.systemd_service:
    name: nftables.service
    state: reloaded
